"""Repository discovery capabilities: files, search, read, repo map, outline."""

from __future__ import annotations

from .files import (
    DEFAULT_RG_EXCLUDES,
    DEFAULT_SKIP_PARTS,
    SENSITIVE_RG_EXCLUDES,
    SENSITIVE_RG_REINCLUDES,
    add_rg_excludes,
    is_skipped,
    list_repo_files,
    repo_root,
    validated_scopes,
)
from .models import PackageManifest
from .outline import (
    OutlineParseError,
    OutlineRequest,
    OutlineResult,
    OutlineSymbol,
    outline,
    python_outline,
)
from .read import (
    ReadContinuation,
    ReadItem,
    ReadLine,
    ReadRequest,
    ReadResult,
    ReadWindow,
    RequestedRange,
    read,
)
from .rendering import (
    render_outline,
    render_read,
    render_search,
)
from .search import (
    ContextLine,
    MatchFileSummary,
    OmittedCounts,
    SearchFile,
    SearchFollowUp,
    SearchHit,
    SearchRequest,
    SearchResult,
    SearchResume,
    SnippetLine,
    SourceSnippet,
    compact_search_wire,
    parse_json_lines,
    safe_int,
    search,
)

__all__ = [
    "ContextLine",
    "DEFAULT_RG_EXCLUDES",
    "DEFAULT_SKIP_PARTS",
    "MatchFileSummary",
    "OmittedCounts",
    "OutlineParseError",
    "OutlineRequest",
    "OutlineResult",
    "OutlineSymbol",
    "PackageManifest",
    "ReadContinuation",
    "ReadItem",
    "ReadLine",
    "ReadRequest",
    "ReadResult",
    "ReadWindow",
    "RequestedRange",
    "SENSITIVE_RG_EXCLUDES",
    "SENSITIVE_RG_REINCLUDES",
    "SearchFollowUp",
    "SearchFile",
    "SearchHit",
    "SearchRequest",
    "SearchResult",
    "SearchResume",
    "SnippetLine",
    "SourceSnippet",
    "add_rg_excludes",
    "compact_search_wire",
    "files",
    "is_skipped",
    "list_repo_files",
    "outline",
    "python_outline",
    "python_outline",
    "parse_json_lines",
    "read",
    "render_outline",
    "render_read",
    "render_search",
    "repo_root",
    "safe_int",
    "search",
    "validated_scopes",
]
