"""Typed navigation and inspection capability.

Providers own everything language-specific (process launches, parsers,
runtimes); inspection orchestrates typed provider outcomes and explicit
edit-bundle construction.
"""

from __future__ import annotations

from .inspect import inspect, render_inspect
from .models import (
    AMBIGUOUS,
    NOT_FOUND,
    PARTIAL,
    PROVIDER_FAILED,
    RESOLVED,
    CandidateRef,
    DeclarationSpan,
    EditBundle,
    EditCoverage,
    InspectRequest,
    InspectResult,
    NavigationPayload,
    NavigationProvider,
    NavigationRequest,
    ProviderMetadata,
    PythonContinuation,
    PythonOverview,
    PythonReference,
    PythonReferenceSection,
    ReferenceEvidence,
    ReferenceItem,
    TargetIdentity,
    TypeScriptContinuation,
    TypeScriptLocation,
    TypeScriptNav,
    TypeScriptNavRequest,
    TypeScriptSection,
)
from .providers import (
    LexicalFallbackProvider,
    PythonProvider,
    TypeScriptProvider,
    python_outline,
    python_symbol_overview,
    render_python_overview,
    render_ts_nav,
    ts_nav,
)
from .resolution import (
    LANGUAGE_PROVIDERS,
    LEXICAL_FALLBACK,
    SymbolResolution,
    resolve_symbol,
)

__all__ = [
    "AMBIGUOUS",
    "CandidateRef",
    "DeclarationSpan",
    "EditBundle",
    "EditCoverage",
    "InspectRequest",
    "InspectResult",
    "LANGUAGE_PROVIDERS",
    "LEXICAL_FALLBACK",
    "LexicalFallbackProvider",
    "NOT_FOUND",
    "NavigationPayload",
    "NavigationProvider",
    "NavigationRequest",
    "PARTIAL",
    "PROVIDER_FAILED",
    "ProviderMetadata",
    "PythonContinuation",
    "PythonOverview",
    "PythonProvider",
    "PythonReference",
    "PythonReferenceSection",
    "RESOLVED",
    "ReferenceEvidence",
    "ReferenceItem",
    "SymbolResolution",
    "TargetIdentity",
    "TypeScriptContinuation",
    "TypeScriptLocation",
    "TypeScriptNav",
    "TypeScriptNavRequest",
    "TypeScriptProvider",
    "TypeScriptSection",
    "inspect",
    "python_outline",
    "python_symbol_overview",
    "render_inspect",
    "render_python_overview",
    "render_ts_nav",
    "resolve_symbol",
    "ts_nav",
]
