"""Typed navigation and inspection capability.

Providers own everything language-specific (process launches, parsers,
runtimes); inspection orchestrates typed provider outcomes and explicit
edit-bundle construction.
"""

from __future__ import annotations

from .inspect import inspect, render_inspect
from .models import (
    AMBIGUOUS,
    NOT_FOUND,
    PARTIAL,
    PROVIDER_FAILED,
    RESOLVED,
    CandidateRef,
    DeclarationSpan,
    EditBundle,
    EditCoverage,
    EditInspection,
    EvidencePage,
    InspectRequest,
    InspectResult,
    NavigationPayload,
    NavigationProvider,
    NavigationRequest,
    OutlineInspection,
    ProviderMetadata,
    PythonContinuation,
    PythonOverview,
    PythonReference,
    PythonReferenceSection,
    ReferenceEvidence,
    ReferenceRecord,
    SourceInspection,
    SymbolCandidate,
    SymbolEvidence,
    SymbolInspection,
    TargetIdentity,
    TypeScriptCandidateSearch,
    TypeScriptContinuation,
    TypeScriptLocation,
    TypeScriptLocations,
    TypeScriptNav,
    TypeScriptNavRequest,
    TypeScriptSection,
    TypeScriptSymbolOverview,
)
from .providers import (
    LexicalFallbackProvider,
    PythonProvider,
    TypeScriptProvider,
    python_symbol_overview,
    render_python_overview,
    render_ts_nav,
    ts_nav,
    ts_nav_from_payload,
)
from .resolution import (
    LANGUAGE_PROVIDERS,
    LEXICAL_FALLBACK,
    SymbolResolution,
    query_provider,
    resolve_symbol,
)

__all__ = [
    "AMBIGUOUS",
    "CandidateRef",
    "DeclarationSpan",
    "EditBundle",
    "EditCoverage",
    "EditInspection",
    "EvidencePage",
    "InspectRequest",
    "InspectResult",
    "LANGUAGE_PROVIDERS",
    "LEXICAL_FALLBACK",
    "LexicalFallbackProvider",
    "NOT_FOUND",
    "NavigationPayload",
    "NavigationProvider",
    "NavigationRequest",
    "PARTIAL",
    "PROVIDER_FAILED",
    "OutlineInspection",
    "ProviderMetadata",
    "PythonContinuation",
    "PythonOverview",
    "PythonProvider",
    "PythonReference",
    "PythonReferenceSection",
    "RESOLVED",
    "ReferenceEvidence",
    "ReferenceRecord",
    "SourceInspection",
    "SymbolCandidate",
    "SymbolEvidence",
    "SymbolInspection",
    "SymbolResolution",
    "TargetIdentity",
    "TypeScriptCandidateSearch",
    "TypeScriptContinuation",
    "TypeScriptLocation",
    "TypeScriptLocations",
    "TypeScriptNav",
    "TypeScriptNavRequest",
    "TypeScriptProvider",
    "TypeScriptSection",
    "TypeScriptSymbolOverview",
    "inspect",
    "python_symbol_overview",
    "render_inspect",
    "render_python_overview",
    "render_ts_nav",
    "ts_nav_from_payload",
    "query_provider",
    "resolve_symbol",
    "ts_nav",
]
